# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'CompilationProblem' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AWSPredictionsPlugin'

  # Pods for CompilationProblem

end
